name: "Terraform Apply"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform plan
        run: terraform -chdir=terraform plan -input=false

      # - name: Terraform apply
      #   run: terraform -chdir=terraform apply -auto-approve -input=false

      - name: Terraform Plan and Apply for each workspace
        run: terraform -chdir=terraform apply  -auto-approve -var-file=stage.tfvars
        # |

        #   for ws in "dev.tfvars" "stage.tfvars" "prod.tfvars"; do
        #     echo "=== Processing the workspace: $ws ==="

            


        #     terraform -chdir=terraform apply  -auto-approve -var-file=$ws

        #     echo "=== Workspace $ws completed ==="
        #   done

#       - name: Terraform Apply and Plan Multi-Workspace
#         run: |
#           cd terraform

#           WORKSPACES=("dev" "stage" "prod")

#           for ws in "${WORKSPACES[@]}"; do
#             echo "=== "Processing the workspace: $ws" ==="

#             terraform workspace select $ws || terraform workspace new $ws

#             terraform plan -input=false
#             terraform apply --auto-approve -out=tfplan_$ws

#             echo "=== Workspace $ws completed ==="
#           done

# #terraform apply -auto-approve tfplan_$ws
# # terraform destroy -auto-approve
