name: "Terraform Apply"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Plan and Apply per Workspace
        run: |
          cd terraform
          
          # Define your environments
          WORKSPACES=("dev" "stage" "prod")
          
          for ws in "${WORKSPACES[@]}"; do
            echo "=== Processing environment: $ws ==="
            
            # Set Terraform Cloud workspace
            export TF_WORKSPACE="${ws}"
            
            # Run Terraform commands for this workspace
            terraform init -reconfigure
            terraform plan -input=false -out=tfplan
            
            # Comment out for safety, uncomment when ready
            # terraform apply -auto-approve tfplan
            
            echo "=== Environment $ws completed ==="
          done