name: "Terraform Apply"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: "z1tgugxB2UCuOQ.atlasv1.WkFxkqp9aXVekfyeZiIKQtZBWyDbZZRx048MB4pj7RzbZI3pFHWPev6aCFtPM0PNe4o"


      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply and Plan Multi-Workspace
        run: |
          cd terraform

          WORKSPACES=("dev" "stage" "prod")

          for ws in "${WORKSPACES[@]}"; do
            echo "=== "Processing the workspace: $ws" ==="
            
            
            terraform workspace select $ws || terraform workspace new $ws
            
            terraform init
            # terraform plan -out=tfplan_$ws
            terraform destroy -auto-approve 
            
            echo "=== Workspace $ws completed ==="
          done
#terraform apply -auto-approve tfplan_$ws
# terraform destroy -auto-approve
