# name: "Terraform Apply"

# on:
#   push:
#     branches: ["master"]

# permissions:
#   contents: read

# jobs:
#   terraform:
#     name: "Terraform"
#     runs-on: ubuntu-latest
#     environment: production
    
#     defaults:
#       run:
#         shell: bash

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v1

#       - name: Run SSH Key Generator
#         uses: ibrahim-a-developper/github-ssh-key-generator@master
#         with:
#           email: toureibrahimd2@gmail.com
      
#       - name: Terraform Init
#         run: terraform -chdir=terraform init

#       - name: Setup Workspace
#         run: |
#           terraform -chdir=terraform workspace new prod || echo "Workspace prod already exists"
#           terraform -chdir=terraform workspace select prod
#           echo "Using workspace: $(terraform -chdir=terraform workspace show)"

#       - name: Terraform Validate and Plan
#         env:
#           TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
#         run: |
#           terraform -chdir=terraform validate
#           terraform -chdir=terraform plan -input=false

#       - name: Terraform Apply
#         env:
#           TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
#         run: terraform -chdir=terraform apply -auto-approve