# name: "Terraform Plan"

# on:
#   push:
#     branches: ["master", "dev", "stage"]
#   pull_request:

# permissions:
#   contents: read

# jobs:
#   terraform:
#     name: "Terraform"
#     runs-on: ubuntu-latest
#     environment: production

#     defaults:
#       run:
#         shell: bash

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v1

#       - name: Run my local action
#         uses: ibrahim-a-developper/github-ssh-key-generator@master
#         with:
#           email: toureibrahimd2@gmail.com

      
#       - name: Terraform Init
#         run: terraform -chdir=terraform init

#       - name: Create Terraform Workspaces
#         run: |
#           terraform -chdir=terraform workspace new dev || echo "Workspace dev already exists"
#           terraform -chdir=terraform workspace new stage || echo "Workspace stage already exists"
#           terraform -chdir=terraform workspace new prod || echo "Workspace prod already exists"
#           terraform -chdir=terraform workspace select dev

   

#       - name: Terraform Validate
#         run: terraform -chdir=terraform validate

#       - name: Terraform Format
#         run: terraform -chdir=terraform fmt -check

#       - name: Terraform Plan
#         env:
#           TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
#         run: terraform -chdir=terraform plan -input=false

    