name: "Terraform"

on:
  push:
    branches: ["master", "development", "stage"]
  pull_request:
  # pull_request:
  #   # The branches below must be a subset of the branches above
  #   branches: ["master"]

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Run my local action
        uses: ibrahim-a-developper/github-ssh-key-generator@master
        with:
          email: toureibrahimd2@gmail.com

      
      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Create Terraform Workspaces
        run: |
          terraform -chdir=terraform workspace new dev || echo "Workspace dev already exists"
          terraform -chdir=terraform workspace new stage || echo "Workspace stage already exists"
          terraform -chdir=terraform workspace new prod || echo "Workspace prod already exists"
          terraform -chdir=terraform workspace select dev

      - name: Select Terraform Workspace
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
            terraform -chdir=terraform workspace select prod
          elif [[ ${{ github.ref }} == 'refs/heads/stage' ]]; then
            terraform -chdir=terraform workspace select stage
          else
            terraform -chdir=terraform workspace select dev
          fi

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Terraform Format
        run: terraform -chdir=terraform fmt -check

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -input=false \
            -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \ 
            -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var "aws_region=${{ secrets.AWS_REGION }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform -chdir=terraform apply -auto-approve -input=false \
            -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var "aws_region=${{ secrets.AWS_REGION }}"